### ISSUE TITLE
You don't need react, react-dom, nwb as dependencies.

### ISSUE THREAD

**Issue by timkindberg** [zagaran/django-react-loader#2]
I don't see anywhere in your code that justifies having those three libraries as dependencies. Meaning, I should be able to install django-react-loader without needing to get `nwb` (it's the main one that I'd rather not install). You can move those over to devDependencies to indicate that they are only needed for local development and testing.

**Comment by jklingen92** [comment]
Hey @timkindberg,

Thanks for looking at the package! Obviously we haven't been developing it very actively, but your attention is much appreciated.

I have a few questions. I agree that `nwb` doesn't need to be in dependencies (actually, I'm going to update the README because it needs to be installed globally and called from the command line).

Now while none of the code in this package technically imports react or react-dom, we do generate code that depends on react:

https://github.com/zagaran/django-react-loader/blob/master/src/django-react-loader.js#L3

Since this is the npm package part of the django react integration, we felt that it was an appropriate place to require react to be installed. Obviously if you're trying to use this package, you'd probably already have it installed, but we're still technically producing code that will require react when it compiles. Does that address your concern?

**Comment by timkindberg** [comment]
Ah ok I did not see that particular file 👍 Thank you
